title: Hang Yang's Homepage
page-top-title: Hang Yang
top-section-bg-text: Data Science and Statistics
home-subtitle: Hang Yang&ensp;|&ensp;杨航
copyright-text: '&copy; Hang Yang 2023-2024. All Rights Reserved.'
